"""new_db_v1

Revision ID: 58a1d2629e3c
Revises: 
Create Date: 2024-03-28 22:21:47.052355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a1d2629e3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('state_name', sa.String(length=30), nullable=False),
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_zip'), 'locations', ['zip'], unique=True)
    op.create_table('delivery_cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_car', sa.String(), nullable=False),
    sa.Column('current_location', sa.Integer(), nullable=False),
    sa.Column('carrying', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('carrying >= 0 and carrying <= 1000', name='chk_carrying'),
    sa.ForeignKeyConstraint(['current_location'], ['locations.zip'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number_car')
    )
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pick_up', sa.Integer(), nullable=False),
    sa.Column('delivery', sa.Integer(), nullable=False),
    sa.Column('weight', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.CheckConstraint('weight >= 0 and weight <= 1000', name='chk_weight'),
    sa.ForeignKeyConstraint(['delivery'], ['locations.zip'], ),
    sa.ForeignKeyConstraint(['pick_up'], ['locations.zip'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    op.drop_table('delivery_cars')
    op.drop_index(op.f('ix_locations_zip'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
